#! /bin/sh

PATH=/bin:/sbin:/usr/bin:/usr/sbin
runlevel=S
prelevel=N
umask 022

videoDriverFile="/dev/video2"

export PATH runlevel prelevel

mount -a
mkdir /dev/pts
mount -t devpts devpts /dev/pts
mount -t usbfs  usbfs /proc/bus/usb
echo /sbin/mdev > /proc/sys/kernel/hotplug

mdev -s
mkdir -p /var/lock
mkdir -p /var/empty
mkdir -p /var/run
mkdir -p /var/tmp
mkdir -p /var/log
hwclock -s

/bin/hostname -F /etc/sysconfig/HOSTNAME
mkdir /dev/snd  
ln /dev/controlC0 /dev/snd/controlC0  
ln /dev/pcmC0D0c /dev/snd/pcmC0D0c  
ln /dev/pcmC0D0p /dev/snd/pcmC0D0p  
ln /dev/timer /dev/snd/timer 

/etc/rc.d/init.d/alsaconf start

hwclock -s
udhcpc -i eth0&
net_manager&
remote_login&

insmod /driver/rt5370sta.ko
insmod /driver/leddriver.ko
insmod /driver/dht11.ko

if [ ! -c "/dev/ttyUSB0" ]; then
	usb-modeswitch -c /etc/usb_modeswitch.d/12d1\:1446 
fi

music_control&
tcp_data_transport&
dev_manage&

chmod 775 /usr/ftp
chmod 777 /usr/ftp/music
vsftpd /etc/vsftpd/vsftpd.conf&

cd /usr/bin
goahead &
cd /

if [ -c "$videoDriverFile" ]; then
video_server
else
echo "no video camera found!" > /dev/tty1
fi


